server:
  port: 11000


spring:
  rabbitmq:
    host: localhost
    username: admin
    password: admin

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 500000
        readTimeout: 500000
        loggerLevel: basic
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 500000

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  eureka:
    enabled: true